### ISSUE TITLE
symbolator not working with sphinx 4.x

### ISSUE THREAD

**Issue by oholimoli** [kevinpt/symbolator#17]
Symbolator is not working with Sphinx 4.x.

```
>>> import symbolator_sphinx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/symbolator_sphinx/__init__.py", line 1, in <module>
    from .symbolator_sphinx import *
  File "/usr/local/lib/python3.8/site-packages/symbolator_sphinx/symbolator_sphinx.py", line 33, in <module>
    from sphinx.util.osutil import ensuredir, ENOENT, EPIPE, EINVAL
ImportError: cannot import name 'ENOENT' from 'sphinx.util.osutil' (/usr/local/lib/python3.8/site-packages/sphinx/util/osutil.py)
```

It should be possible to fix this error.

The line in: https://github.com/kevinpt/symbolator/blob/master/symbolator_sphinx/symbolator_sphinx.py#L33

must be changed to: `from errno import ENOENT, EPIPE, EINVAL`

https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter/commit/252a0b0fa097686dae84e8d7c39f901dc010a531

**Comment by Paebbels** [comment]
Maybe the fork https://github.com/hdl/symbolator can help you.
